version: '3.7'
services: 
  rabbitmq:
    image: rabbitmq:3.7.18-management
    container_name: rabbitmq
    networks:
    - dev
    ports: 
      - "15672:15672"
      - "5672:5672"
  go:
    image: golang:1.13-stretch
    container_name: go
    command: sleep infinity
    networks:
      - dev
    volumes:
      - .:/go/src/github.com/mistermoe/rabbit

networks:
  dev:
    